/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AIAssistantMenu: typeof import('./../novel/components/GlobalAIAssistant/AIAssistantMenu.vue')['default']
    AITaskConfigModal: typeof import('./../novel/components/GlobalAIAssistant/AITaskConfigModal.vue')['default']
    EditorAIPanel: typeof import('./../novel/components/editor/EditorAIPanel.vue')['default']
    EditorContent: typeof import('./../novel/components/editor/EditorContent.vue')['default']
    EditorSidebar: typeof import('./../novel/components/editor/EditorSidebar.vue')['default']
    GlobalAIAssistant: typeof import('./../novel/components/GlobalAIAssistant/index.vue')['default']
    NovelDashboardSidebar: typeof import('./../novel/components/NovelDashboardSidebar.vue')['default']
    NovelManagementSidebar: typeof import('./../novel/components/NovelManagementSidebar.vue')['default']
    NovelSidebar: typeof import('./../novel/components/NovelSidebar.vue')['default']
    PromptSidebar: typeof import('./../prompt/components/PromptSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsSidebar: typeof import('./../settings/components/SettingsSidebar.vue')['default']
  }
}
